module.exports = {
  apps: [
    {
      name: 'eightblock-backend',
      cwd: '/var/www/eightblock/backend',
      script: 'tsx',
      args: 'src/server.ts',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/www/eightblock/logs/backend-error.log',
      out_file: '/var/www/eightblock/logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '1G',
      min_uptime: '10s',
      max_restarts: 10,
      autorestart: true,
      watch: false,
    },
    {
      name: 'eightblock-frontend',
      cwd: '/var/www/eightblock/frontend',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3000',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/www/eightblock/logs/frontend-error.log',
      out_file: '/var/www/eightblock/logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '1G',
      min_uptime: '10s',
      max_restarts: 10,
      autorestart: true,
      watch: false,
    },
  ],
};
