import { createRouter } from '../utils/async-router.js';
import articleRoutes from '../routes/article-routes.js';
import commentRoutes from '../routes/comment-routes.js';
import likeRoutes from '../routes/like-routes.js';
import subscriptionRoutes from '../routes/subscription-routes.js';
import newsletterRoutes from '../routes/newsletter-routes.js';
import tagRoutes from '../routes/tag-routes.js';
import authRoutes from '../routes/auth-routes.js';
import userRoutes from '../routes/user-routes.js';
import uploadRoutes from '../routes/upload-routes.js';
import bookmarkRoutes from '../routes/bookmark-routes.js';
import portfolioRoutes from '../routes/portfolio-routes.js';
import authorRoutes from '../routes/author-routes.js';
import analyticsRoutes from '../routes/analytics-routes.js';
import webhookRoutes from '../routes/webhook-routes.js';
import supportWalletRoutes from '../routes/support-wallet-routes.js';
import categoryRoutes from '../routes/category-routes.js';
import emailTemplateRoutes from '../routes/email-template-routes.js';

const router = createRouter();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/upload', uploadRoutes);
router.use('/articles/:articleId/comments', commentRoutes);
router.use('/articles/:articleId/likes', likeRoutes);
router.use('/articles', articleRoutes);
router.use('/tags', tagRoutes);
router.use('/categories', categoryRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/newsletters', newsletterRoutes);
router.use('/email-templates', emailTemplateRoutes);
router.use('/bookmarks', bookmarkRoutes);
router.use('/portfolio', portfolioRoutes);
router.use('/support-wallets', supportWalletRoutes);
router.use('/authors', authorRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/webhooks', webhookRoutes);

export default router;
